### ISSUE TITLE
Add min_distance parameter

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/odjitter#1]
Will close https://github.com/ITSLeeds/atumie/issues/84 (to be open sourced). Discussed today with @joeytalbot.

**Comment by dabreegster** [comment]
This will be the minimum distance between `o` and `d` here: https://github.com/dabreegster/odjitter/blob/fa2357f0bb3c7e207027789dddff2b7a3d8f5c48/src/lib.rs#L144

What should the default be -- 1 meter?

**Comment by Robinlovelace** [comment]
> What should the default be -- 1 meter?

I think that's a good shout.

**Comment by dabreegster** [comment]
> No default value. Solid and puts the responsibility on the user IIRC.

Oops, I guess I missed your comment on the PR! If you want to force the user to set it, just nix the `default_value` bit. I'm not sure users starting out want to think about this level of detail, but it could be good

**Comment by Robinlovelace** [comment]
> just nix the `default_value` bit.

No I think 1m is safe, unless people are modelling and (or perhaps baby?) mobility : )
