### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/odjitter#12]
This should probably be seen in context of broader meta-issue on documentation but opening this after changes in #11. My plan is to:

- [x] Switch from .Rmd source to .qmd for source to reduce dependencies
- [x] Tidy-up (no leftover files)
- [ ] Explain and demonstrate with a reproducible example the use of new subpoints arguments using the schools dataset

Can work on this later today but happy to hold horses if other features, e.g. addition of `weight_key_origins` and `weight_key_destinations` arguments, are in the pipeline. Note to self: most recent version of the pkg has the following arguments:

```
odjitter --help
odjitter 0.1.0
Dustin Carlino <dabreegster@gmail.com
Disaggregate origin/destination data from zones to points

USAGE:
    odjitter [OPTIONS] --od-csv-path <OD_CSV_PATH> --zones-path <ZONES_PATH> --output-path <OUTPUT_PATH> --disaggregation-threshold <DISAGGREGATION_THRESHOLD>

OPTIONS:
        --destination-key <DESTINATION_KEY>
            Which column in the OD row specifies the zone where trips ends? [default: geo_code2]

        --disaggregation-key <DISAGGREGATION_KEY>
            Which column in the OD row specifies the total number of trips to disaggregate?
            [default: all]

        --disaggregation-threshold <DISAGGREGATION_THRESHOLD>
            What's the maximum number of trips per output OD row that's allowed? If an input OD row
            contains less than this, it will appear in the output without transformation. Otherwise,
            the input row is repeated until the sum matches the original value, but each output row
            obeys this maximum

    -h, --help
            Print help information

        --min-distance-meters <MIN_DISTANCE_METERS>
            Guarantee that jittered points are at least this distance apart [default: 1.0]

        --od-csv-path <OD_CSV_PATH>
            The path to a CSV file with aggregated origin/destination data

        --origin-key <ORIGIN_KEY>
            Which column in the OD row specifies the zone where trips originate? [default:
            geo_code1]

        --output-path <OUTPUT_PATH>
            The path to a GeoJSON file where the disaggregated output will be written

        --rng-seed <RNG_SEED>
            By default, the output will be different every time the tool is run, based on a
            different random number generator seed. Specify this to get deterministic behavior,
            given the same input

        --subpoints-destinations-path <SUBPOINTS_DESTINATIONS_PATH>
            The path to a GeoJSON file to use for sampling subpoints for destination zones. If this
            isn't specified, random points within each zone will be used instead

        --subpoints-origins-path <SUBPOINTS_ORIGINS_PATH>
            The path to a GeoJSON file to use for sampling subpoints for origin zones. If this isn't
            specified, random points within each zone will be used instead

    -V, --version
            Print version information

        --zone-name-key <ZONE_NAME_KEY>
            In the zones GeoJSON file, which property is the name of a zone [default: InterZone]

        --zones-path <ZONES_PATH>
            The path to a GeoJSON file with named zones
```

**Comment by dabreegster** [comment]
Weighted subpoints and a second disaggregation command are coming, but maybe not by today. I'd guess both are additive to the docs, so switching to qmd shouldn't get in the way of anything

**Comment by Robinlovelace** [comment]
Looking into it now.

**Comment by Robinlovelace** [comment]
Discovery: after rebuilding the source doc in the commit above I get this: 

![image](https://user-images.githubusercontent.com/1825120/152997179-960e665c-da90-4e54-ba31-462ecf0067d3.png)

It's html, could be basis of a nice website, but working on getting the .md updated...

**Comment by Robinlovelace** [comment]
Looking at the docs: https://quarto.org/docs/authoring/markdown-basics.html

**Comment by Robinlovelace** [comment]
```
format: gfm
```

In the header will solve it I think. https://quarto.org/docs/output-formats/gfm.html#gfm-format

**Comment by Robinlovelace** [comment]
Update while writing the this: great error message with clear fix:

```
Error: data/od_schools.csv doesn't have a all column or the value isn't numeric; set disaggregation_key properly
```

**Comment by Robinlovelace** [comment]
And another one, this is good:

```
Error: data/od_schools.csv doesn't have a geo_code1 column; set origin_key properly
```

**Comment by dabreegster** [comment]
Glad the error messages are proving useful! Very frustratingly, all filesystem errors in Rust by default are next to worthless -- they just say "no such file or directory" without including the path. So if you're ever working on a Rust project, I'd recommend https://crates.io/crates/fs-err as a workaround

**Comment by Robinlovelace** [comment]
Good visualisation for the docs, may remove from README but here as a placeholder to tidy up:

![image](https://user-images.githubusercontent.com/1825120/153021585-44cc107e-0183-4cc3-b7e7-0f72c4fd2c01.png)
