### ISSUE TITLE
Can/should odjitter return duplicate geometries?

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/odjitter#38]
As reported by @mem48 in https://github.com/nptscot/npt/issues/32 we're seeing a few (0.04% in our example data) results that are duplicated geometries. Is this an upstream issue in the Rust code (I suspect so but not sure)?

**Comment by dabreegster** [comment]
Can you give a repro? What subsampling policy are you giving? Are you feeding in a subpoint file with any repeats? Etc

**Comment by Robinlovelace** [comment]
Repro incoming!

**Comment by Robinlovelace** [comment]
``` r
## code to prepare `duplicate_geometries` dataset goes here

remotes::install_github("dabreegster/odjitter", subdir = "r")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'odjitter' from a github remote, the SHA1 (00ba4b08) has not changed since last install.
#>   Use `force = TRUE` to force installation

?odjitter::jitter

# usethis::use_data(duplicate_geometries, overwrite = TRUE)
od = readr::read_csv("https://github.com/dabreegster/odjitter/raw/main/data/od.csv")
#> Rows: 49 Columns: 11
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (2): geo_code1, geo_code2
#> dbl (9): all, from_home, train, bus, car_driver, car_passenger, bicycle, foo...
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
zones = sf::read_sf("https://github.com/dabreegster/odjitter/raw/main/data/zones.geojson")
road_network = sf::read_sf("https://github.com/dabreegster/odjitter/raw/main/data/road_network.geojson")
od_jittered = jitter(od, zones, subpoints = road_network)
#> Error in jitter(od, zones, subpoints = road_network): unused argument (subpoints = road_network)
# basic example to test it's a hard-to-find issue:
summary(duplicated(od_jittered$geometry))
#> Error in duplicated(od_jittered$geometry): object 'od_jittered' not found

# Larger example:
od_jittered = jitter(
  od,
  zones,
  subpoints = road_network,
  disaggregation_threshold = 1,
  show_command = TRUE
)
#> Error in jitter(od, zones, subpoints = road_network, disaggregation_threshold = 1, : unused arguments (subpoints = road_network, disaggregation_threshold = 1, show_command = TRUE)
summary(duplicated(od_jittered$geometry))
#> Error in duplicated(od_jittered$geometry): object 'od_jittered' not found
```

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dabreegster** [comment]
Thanks for the one-liner!

https://github.com/dabreegster/odjitter/blob/00ba4b0885f2652f0c51d41d4b42c66e48b62315/src/lib.rs#L437
For weighted subpoints subsampling, nothing prevents this from picking the same points repeatedly. There's a TODO about maybe sampling with replacement.

https://github.com/dabreegster/odjitter/blob/00ba4b0885f2652f0c51d41d4b42c66e48b62315/src/lib.rs#L430
For the random points subsampling, we choose uniformly at random in the polygon. Nothing prevents the same point from being chosen.


So, this is expected behavior right now. I've lost all context on the original requirements. If we want to guarantee no duplicates in the output:

- We could add a new flag to specify that
- We need to decide where we want to disallow duplicate (o, d) pair, or disallow ever using the same origin or the same destination, even if the pair is different
- It may change the performance properties, depending how frequently collision happens, and memory requirements, if we need to look for duplicates

**Comment by Robinlovelace** [comment]
Many thanks for the quick and detailed response Dustin. My thoughts on your suggestions:

> * We could add a new flag to specify that
> 

:+1: 

>     * We need to decide where we want to disallow duplicate (o, d) pair, or disallow ever using the same origin or the same destination, even if the pair is different
> 

Only need to disallow same pairs. Repeated origins and destinations are fine, it's just the combo that we need to avoid.

>     * It may change the performance properties, depending how frequently collision happens, and memory requirements, if we need to look for duplicates

Yes checking for duplicate pairs will have a perf impact I guess. Setting it as an optional flag that is off by default will overcome that.

**Comment by dabreegster** [comment]
Do we want to deduplicate just based on the two points, or do the other keys/properties matter too? ie, is this allowed in the output or not?

```
[{origin: [0, 0], destination: [1, 1], mode: bike},
{origin: [0, 0], destination: [1, 1], mode: drive}]
```

**Comment by Robinlovelace** [comment]
> Do we want to deduplicate just based on the two points, or do the other keys/properties matter too? ie, is this allowed in the output or not?

Just based on 2 points is good for now.

**Comment by mem48** [comment]
@Robinlovelace is this implemented in the R package? Would like to use on NPT

**Comment by Robinlovelace** [comment]
> @Robinlovelace is this implemented in the R package? Would like to use on NPT

No but should be quick to implement. Will give it a go now.

**Comment by Robinlovelace** [comment]
Slightly updated version: 

```
odjitter jitter --od-csv-path data/od.csv --zones-path data/zones.geojson --zone-name-key InterZone --origin-key geo_code1 --destination-key geo_code2 --subpoints-origins-path data/road_network.geojson --subpoints-destinations-path data/road_network.geojson --disaggregation-key all --disaggregation-threshold 1 --rng-seed 68279 --output-path data/od_jittered.geojson
```
