### ISSUE TITLE
odjitter can hang when duplicate pairs are disallowed

### ISSUE THREAD

**Issue by Robinlovelace** [dabreegster/odjitter#49]
Reproducible example: unzip the zip below and run the following:

[odjitter-example.zip](https://github.com/dabreegster/odjitter/files/12066754/odjitter-example.zip)

```bash
odjitter jitter --od-csv-path odjitter-example/od.csv --zones-path odjitter-example/zones.geojson --zone-name-key CSOED_3409 --origin-key O --destination-key D --subpoints-origins-path odjitter-example/subpoints_origins.geojson --subpoints-destinations-path odjitter-example/subpoints_destinations.geojson --disaggregation-key interaction --disaggregation-threshold 50 --rng-seed 46569 --deduplicate-pairs  --output-path odjitter-example/od_jittered.geojson
```

**Comment by Robinlovelace** [comment]
Another instance of this it seems: https://github.com/nptscot/npt/pull/194

**Comment by dabreegster** [comment]
I added some debugging:

Sampling 47 times from jitter20020 (221 points) to jitter173362 (1 points)
Sampling 116 times from jitter20027 (256 points) to jitter173362 (1 points)
Sampling 215 times from jitter20011 (541 points) to jitter173362 (1 points)
Sampling 226 times from jitter20015 (118 points) to jitter173362 (1 points)

That last line is the problem. You're asking for 226 unique/deduplicated pairs between 118 origins and 1 destination. That's impossible; I'll change to halting with a clear error.

**Comment by dabreegster** [comment]
The tool will now stop very quickly with `Error: 226 unique pairs requested from jitter20015 (118 subpoints) to jitter173362 (1 subpoints), but this is impossible`.

I don't know what you want to do in this situation. If you want to give up on deduplicated points in this case, or to reduce the requested count, or something else, we could add options, but it makes the API more complex.

**Comment by Robinlovelace** [comment]
Great fix Dustin. Yes, I wondered if it was due to there being insufficient combinations. Arguably the dedupe setting should be `true` by default to prevent people getting what they think are different desire lines in situations in which there are too few subpoints.

The error message looks good and it's on the users (me and @mem48 atm ; ) to provide good inputs.

There could be an escape valve that randomly samples points from thin air but that feels like mission creep. I'm 100% happy with and very grateful for this fix, which will show up on the R side too I believe. 

On a different topic, I'd like to revisit properly wiring up the R/Rust interface inspired by @josiahParry's work on `rsgeo`: worth doing with `rextendendr` by your estimation? Apologies for going off topic and tagging you but thought may be of interest in the pretty small R/Rust geo space!

**Comment by JosiahParry** [comment]
I've just taken a quick perusal of odjitter and it looks like it works by actually reading geometries and then applying the algorithm. 

If the lib could be modified so that there is a function(s) that take a `Vec<geo_types::Geometry>` -> `Vec<Vec<(Point, Point)>>` it would be very easy to wire up with [sfconversions](https://github.com/JosiahParry/sfconversions) lib crate and thus extendr. 

Right now it looks like odjitter is strictly a cli tool and not a library. That change would be needed and from there it would be easy(ish) to make into an R package.

**Comment by Robinlovelace** [comment]
Amazing thanks Josiah! Will have a think, chat with Dustin and look to follow-up in a new issue if worth doing, from learning perspective for sure if time allows although that's a big if atm...
